name = "Spoonpack"
author = "Spooncraft Team"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d94354c18affb8943026c27ed1eedbc4a7053b39997f1eaf559514ea9c05f5a"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
