name = "Spoonpack"
author = "Spooncraft Team"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a63348f2c08e232f3ee8c5066b8fee3d1cbe1fa39ed0e47c4e83c527575d7ee1"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
