name = "Spoonpack"
author = "Spooncraft Team"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7cd1a6311ffdf8559fdd43736184ccb5540a8e9c02b2cfce563298ccb6689c8"

[versions]
forge = "47.2.0"
minecraft = "1.20.1"
